nb_url: "http://10.30.1.226:8000"
nb_token: "dc5b766afda60e647a9fcc384c736a9689da8618"
filter_by:
  device_role: ['Access Switch']
group_by:
  - name
  - device_role.slug
  - site.slug
  - platform.slug
